"""Living wiki inside a repo (docs/wiki/), after the IridescentCraft wiki template.

  init      Scaffold docs/wiki/: conventions, style guide, the seven protocols, home page, doc map,
            session-log index; add a pointer to the repo's CLAUDE.md.
  map       Regenerate map.md: every section of the project's own docs, linked by heading anchor.
  check     Protocol 2: Jev-ranked list of contradicting claim pairs for Claude to review (consistency.py);
            verdicts recorded with `verdict` suppress known false alarms; `selftest` measures recall.
  log       Protocol 5: Jev-triaged session digest -> sessions/logs/<date>-<slug>.md + index row.
  coverage  Protocol 6: crawl relative links from home.md; list orphan pages and broken links.

Existing docs stay where they are; the wiki links into them. Nothing here commits.
"""

from __future__ import annotations

import datetime as dt
import os
import re
import shutil
from collections import Counter, defaultdict
from pathlib import Path

from . import ctx

TEMPLATE = Path(__file__).with_name("wiki_template")
WIKI = Path("docs/wiki")
DOC_GLOBS = ("*.md", "docs/*.md", "docs/**/*.md")
SKIP_DOCS = ("LICENSE.md", "CHANGELOG.md")


def _docs(repo: Path) -> list[ctx.Section]:
    secs = ctx.index(repo, DOC_GLOBS)
    seen, out = set(), []
    for s in secs:  # docs/**/*.md also matches docs/*.md
        if s.id in seen or s.file.startswith(WIKI.as_posix() + "/") or Path(s.file).name in SKIP_DOCS:
            continue
        seen.add(s.id)
        out.append(s)
    return out


def _wiki_and_docs(repo: Path) -> list[ctx.Section]:
    wiki = [s for s in ctx.index(repo, (f"{WIKI.as_posix()}/**/*.md",))
            if "/protocols/" not in s.file and "/meta/" not in s.file and not s.file.endswith(("map.md", "index.md"))]
    return _docs(repo) + wiki


def slug(title: str) -> str:
    """GitHub's heading anchor: lowercase, drop punctuation except '-' and '_', spaces -> '-'."""
    t = re.sub(r"<[^>]+>", "", title.strip().lower())
    return re.sub(r"[^\w\- ]", "", t).replace(" ", "-")


def _anchors(repo: Path, secs: list[ctx.Section]) -> dict[str, str]:
    """Section id -> '#anchor' of the heading that starts it (continuation chunks share their heading's)."""
    out, counts = {}, defaultdict(Counter)
    last: dict[str, str] = {}
    for s in secs:
        first = ctx.section_text(repo, s).split("\n", 1)[0]
        m = re.match(r"^#{1,4}\s+(.*)", first)
        if m:
            base = slug(m.group(1))
            n = counts[s.file][base]
            counts[s.file][base] += 1
            last[s.file] = f"#{base}" + (f"-{n}" if n else "")
        out[s.id] = last.get(s.file, "")
    return out


def _rel(from_file: str, to_file: str) -> str:
    return os.path.relpath(to_file, os.path.dirname(from_file)).replace("\\", "/")


# ---------------------------------------------------------------- map / init

def write_map(repo: Path) -> Path:
    secs = _docs(repo)
    anchors = _anchors(repo, secs)
    here = (WIKI / "map.md").as_posix()
    total = ctx.tok(sum(s.chars for s in secs))
    out = ["# Doc map", "",
           f"Every section of the project's own docs: {len(secs)} sections, ≈{total:,} tokens. Generated by "
           "`jevauto wiki map`; do not edit by hand. To load only what a task needs, use "
           "`jevauto ctx find <repo> \"<task>\"` (or the `context_find` MCP tool) instead of reading whole files.", ""]
    for f in sorted({s.file for s in secs}):
        fs = [s for s in secs if s.file == f]
        out += [f"## [{f}]({_rel(here, f)}) · ≈{ctx.tok(sum(s.chars for s in fs)):,} tokens", ""]
        prev = None
        for s in fs:
            if s.heading == prev:
                continue  # continuation chunk of the same heading: one entry per heading is enough
            prev = s.heading
            depth = min(s.heading.count(" > "), 3)
            leaf = s.heading.split(" > ")[-1]
            size = ctx.tok(sum(x.chars for x in fs if x.heading == s.heading))
            out.append(f"{'  ' * depth}- [{leaf}]({_rel(here, f)}{anchors[s.id]}) · lines {s.start}– · ≈{size:,} tok")
        out.append("")
    path = repo / WIKI / "map.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out), encoding="utf-8", newline="\n")
    return path


def _doc_lines(repo: Path) -> list[str]:
    secs = _docs(repo)
    lines = []
    for f in sorted({s.file for s in secs}):
        fs = [s for s in secs if s.file == f]
        lead = next((s.lead for s in fs if s.lead), "")
        lines.append(f"- [{f}]({_rel((WIKI / 'home.md').as_posix(), f)}) · ≈{ctx.tok(sum(s.chars for s in fs)):,} tokens"
                     + (f" · {lead[:140]}" if lead else ""))
    return lines


PAGES = Path(__file__).with_name("wiki_pages")  # generated pages: str.format templates, filled per project
CLAUDE_POINTER = ("\n## Wiki\n\nLiving docs live in `docs/wiki/` (start at `docs/wiki/home.md`; conventions in "
                  "`docs/wiki/README.md`). At session start, read `docs/wiki/sessions/index.md` and the newest log, then "
                  "load only the doc sections the task needs with `jevauto ctx find` / the `context_find` tool. "
                  "Before ending a session that made decisions, run Protocol 5 (session log).\n")


def _copy_template(wiki: Path, overwrite: bool) -> list[Path]:
    written = []
    for src in TEMPLATE.rglob("*.md"):
        dst = wiki / src.relative_to(TEMPLATE)
        if dst.exists() and not overwrite:
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        written.append(dst)
    return written


def _pages(repo: Path, name: str, summary: str, check_cmd: str | None) -> dict[str, str]:
    handover = (f"- [Handover]({_rel((WIKI / 'home.md').as_posix(), 'docs/HANDOVER.md')}) — where things stand "
                "and the next task\n") if (repo / "docs/HANDOVER.md").exists() else ""
    values = {"name": name, "summary": summary, "start": handover, "docs": "\n".join(_doc_lines(repo)),
              "check": f"`{check_cmd}`" if check_cmd else "see the host README"}
    files = {"README.md": "README.md", "home.md": "home.md", "overview.md": "overview.md",
             "sessions/index.md": "sessions_index.md"}
    return {rel: (PAGES / tmpl).read_text(encoding="utf-8").format(**values) for rel, tmpl in files.items()}


def _point_claude_md(repo: Path, name: str) -> Path | None:
    """Add the wiki pointer to the repo's CLAUDE.md (creating a minimal one, which defers to AGENTS.md if present)."""
    claude = repo / "CLAUDE.md"
    agents = "Read `AGENTS.md` first; it holds this repo's working agreements.\n\n" if (repo / "AGENTS.md").exists() else ""
    text = claude.read_text(encoding="utf-8") if claude.exists() else (
        f"# CLAUDE.md — {name}\n\n{agents}Commits are authored by the repository owner only; never add a "
        "Co-Authored-By trailer or other attribution.\n")
    if "docs/wiki/" in text:
        return None
    claude.write_text(text.rstrip("\n") + "\n" + CLAUDE_POINTER, encoding="utf-8", newline="\n")
    return claude


def init(repo: Path, name: str, summary: str, check_cmd: str | None = None, overwrite: bool = False) -> list[Path]:
    wiki = repo / WIKI
    written = _copy_template(wiki, overwrite)
    for rel, text in _pages(repo, name, summary, check_cmd).items():
        dst = wiki / rel
        if dst.exists() and not overwrite:
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8", newline="\n")
        written.append(dst)
    written.append(write_map(repo))
    claude = _point_claude_md(repo, name)
    return written + ([claude] if claude else [])


# ---------------------------------------------------------------- check (Protocol 2)

def check(repo: Path, top: int = 100):
    """Protocol 2's Jev-ranked review list; see consistency.py for the pipeline and its measured limits."""
    from . import consistency

    return consistency.check(repo, top)


# ---------------------------------------------------------------- log (Protocol 5)

def log(repo: Path, session: str, since: str = "", slug_text: str = "session") -> Path:
    transcript = ctx.resolve_transcript(session)
    handover = repo / "docs" / "HANDOVER.md"
    body, stats = ctx.digest(transcript, since=since, handover=handover if handover.exists() else None)
    today = dt.date.today().isoformat()
    logs = repo / WIKI / "sessions" / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    name = f"{today}-{re.sub(r'[^a-z0-9]+', '-', slug_text.lower()).strip('-')}"
    path = logs / f"{name}.md"
    n = 1
    while path.exists():
        n += 1
        path = logs / f"{name}-{n}.md"
    path.write_text(f"<!-- INTERNAL ONLY -->\n# Session log — {today}\n\n## Summary\n\n<!-- 3–6 bullets written by Claude: what changed, what was "
                    f"decided, what is next. -->\n\n" + body.split("\n", 1)[1], encoding="utf-8", newline="\n")
    index = repo / WIKI / "sessions" / "index.md"
    text = index.read_text(encoding="utf-8")
    row = f"| {today} | [{path.stem}](logs/{path.name}) | {stats['kept_decision']} decisions, {stats['kept_open']} open items |\n"
    head, sep, rest = text.partition("|---|---|---|\n")
    index.write_text(head + sep + row + rest, encoding="utf-8", newline="\n")
    return path


# ---------------------------------------------------------------- coverage (Protocol 6)

_LINK = re.compile(r"\]\(([^)\s]+\.md)(#[^)]*)?\)")


def coverage(repo: Path) -> tuple[list[str], list[tuple[str, str]]]:
    wiki_root = (repo / WIKI).resolve()
    pages = {p.resolve() for p in wiki_root.rglob("*.md")}
    seen, queue, broken = set(), [wiki_root / "home.md"], []
    while queue:
        page = queue.pop()
        if page in seen:
            continue
        seen.add(page)
        # link examples inside code blocks or inline code aren't links
        text = re.sub(r"```[\s\S]*?```|`[^`\n]*`", "", page.read_text(encoding="utf-8", errors="replace"))
        for target, _ in _LINK.findall(text):
            if "://" in target:
                continue
            dest = (page.parent / target).resolve()
            if not dest.exists():
                broken.append((page.relative_to(repo.resolve()).as_posix(), target))
            elif dest in pages:
                queue.append(dest)
    orphans = sorted(p.relative_to(repo.resolve()).as_posix() for p in pages - seen
                     if p.parent.name != "logs")  # logs are reached through sessions/index.md rows
    return orphans, broken
